language: node_js
install:
  - 'npm --prefix ./functions install'
script:
  - 'npm --prefix ./functions lint'
  - 'npm --prefix ./functions test'
deploy:
  provider: firebase
  token:
    secure: AtB4LdiuG026KbJXt8L5A06qn69TmuFOT5486WQe7S5KCaVfKigPs8ZWcM/5ia9uPmrYDJrFuO3Q2x3BaxDLUnuakf656rdZAFhfUs2lkHUp7QhhWzREBt2DfiNiD2uA34kXjVAeF2nS+4umiLBXoTEZ1FEYbJebQMBLd7fa5PjdJjjEWmGQ6DyIeutOskJG8gh+jv0nx2pvTsE06WLqkWS7n2DwcKCVMv9SQIx6Dv9Sor9HDjS8+LOBaQ1nO58FT4/RzyQS+MeoKP1Pk5uaZ6dccyrpXHmXERhOMLpbYA5ffIwKw2mxJlDkPiP60DG5SIK5KeJi4r2EE2qnEW+lIwK8Btmlb5pfPG9NEqUzkjz2D6zvT9wqerpejq6sJ2YCgENYeIKzVqs5RJn0yzIkfcokUCDr3kmvUsaZiw+mng/lEnlK13v6uOrU+ZVRxF7dZIJ0JL8QpzG5T9i2FzUK/G0oDFNd5HQ2kqOs4nmohtBPyZIKoKEcte9Ickjan9jk5HP8daHGcXQiBirpVgdZTmSNQUfvzc1SnYFoT7yECrOdPvMBb5ARAWg/hsIp1KZ1n0Jr0t8H1IHYq8mD+4Sv/P9+XDAuT6aadV0eDc89GymcctoquR7ZrCaC0NFcF1PcITd/QGZg5IqtMks1NtfoBOc23had48UezvweXHqCFV8=
  message: "Successfully deployed to Google Firebase!"
